# Site
name: "BicycleTips.com"
title: "BicycleTips.com"
description: "A cycling website dedicated to bringing you the latest tips, tricks, product and ride reviews, primarily focused on gravel cycling."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
url: "https://www.bicycletips.com"
google_analytics: 'G-Z1EFSG7HWL'
disqus: 'bicycletips'
mailchimp-list: 'https://mailchi.mp/22d2b6b35a2b/bicycletipscom-newsletter'
include: ["_pages"]
permalink: /:title/

facebook:
  app_id: 236378443058488

templatemessage: 'Forked from <a  href="https://www.chrishammond.com/">Chris Hammond</a>''s <a href="https://www.jekyllexample.com">jekyllexample.com</a>.'

# Authors
authors:
  chris:
    name: Chris Hammond
    display_name: Chris Hammond
    first_name: Chris
    last_name: Hammond
    gravatar: eb3fa0a535aad25459bd3299f0b26557
    email: bicycletips@christoc.com
    web: https://www.chrishammond.com
    twitter: https://twitter.com/christoc
    description: "Founder of BicycleTips.com, an avid computer geek, photographer, and amateur bicycle rider. Read more about <a href=\"https://www.chrishammond.com\">Chris Hammond</a>." 

# Plugins
plugins:
  - jekyll_picture_tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives 
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-3356074518164779"
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

picture:
  source: "assets/images"
  output: "assets/images_out"
  suppress_warnings: true
  ignore_missing_images: false
  presets:
    default:
      ppi: [1, 1.5]
      source_medium:
        media: "(min-width: 40em)"
        width: "600"
        height: "300"
      source_default:
        width: "300"

exclude:
  - /assets/images/Content/*


defaults:
  - scope:
      path: ""  # An empty string here means all files
      type: "posts"
    values:
      author: "chris"

